# github action to push the docker container to ecr

on:
  push:
    branches:
      - addGitHubActions

name: Push to prod

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          actions_comment: false
          working_dir: './cdk'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CDK_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CDK_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'     
