# github action to push the docker container to ecr

on:
  push:
    branches:
      - addGitHubActions

name: Push to prod

jobs:
  cdk:
    name: CDK Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdk
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CDK_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CDK_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Module Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('./cdk/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: CDK Deploy
        run: cdk deploy
      
        
